export const ADD_PROJECT_START = 'ADD_PROJECT_START';
export const ADD_PROJECT_FETCHING = 'ADD_PROJECT_FETCHING';
export const ADD_PROJECT_FULFILED = 'ADD_PROJECT_FULFILED';
export const ADD_PROJECT_REJECTED = 'ADD_PROJECT_REJECTED';
export const GET_ALL_PROJECTS_ASYNC_CALL_START = 'GET_ALL_PROJECTS_ASYNC_CALL_START';
export const GET_ALL_PROJECTS_ASYNC_CALL_FULFILED = 'GET_ALL_PROJECTS_ASYNC_CALL_FULFILED';
export const GET_ALL_PROJECTS_ASYNC_CALL_REJECTED = 'GET_ALL_PROJECTS_ASYNC_CALL_REJECTED';