export const CONFIGURATION_LOAD_STARTED = 'CONFIGURATION_LOAD_STARTED';
export const CONFIGURATION_LOAD_SUCCEEDED = 'CONFIGURATION_LOAD_SUCCEEDED';
export const SET_TOKEN_STARTED = 'SET_TOKEN_STARTED';
export const SET_TOKEN_SUCCEEDED = 'SET_TOKEN_SUCCEEDED';